// src/lib/components/Cloth.svelte
<script lang="ts">
import ManShirt from "./ManShirt.svelte";
import WomanDress from "./WomanDress.svelte";
import { genreState } from "../state/state.svelte";
</script>

<div class="cloth">
    {#if genreState.genre === 'male'}
        <ManShirt />
    {:else}
        <WomanDress />
    {/if}
</div>

<style>
.cloth {
    inset: 0;
    position: absolute;
    line-height: 0;
    scale: 1.0125;
}
</style>

// src/dressing-room/components/cloth.tsx
import { ManShirt, WomanDress } from '../clothes';
import styles from './cloth.module.css';

interface Props {
    genre: string;
}

export const Cloth = ({ genre }: Props) => {
    return (
        <div className={ styles.cloth }>
            {
                genre === 'male'
                    ? <ManShirt />
                    : <WomanDress />
            }
        </div>
    );
};
