// src/lib/components/ManShirt.svelte
<script lang="ts">
import { onMount } from 'svelte'
import Pattern from "./Pattern.svelte";
import { pickPatternId } from '../utils/patterns';

let pattern = 'stripes'

const prefix = `shirt-${Math.random().toString(36).slice(2)}-`

onMount(() => {
  pattern = pickPatternId()
})
</script>

<svg
  class="shirt"
  viewBox="0 0 48 100"
  xmlns="http://www.w3.org/2000/svg"
>
  <defs>
    <Pattern {prefix} />
  </defs>

    <g fill={`url(#${prefix}${pattern})`}>
        <path d="M13.4 33.6H7.8l-.5-10c0-.9.2-2.5.7-3.6s3.4-2 4.4-2l6.5-.4c.4 0 1.4-.5 2-2.6h6q0 .6.7 1.6c.3.5 1.2.9 1.6 1 1.7 0 5.5.3 6.8.5 1.7.1 2 .8 3.4 1.6 1.1.6 1 2.4.8 3.2l-.5 11h-5.4l.2-10.4L31.3 50h-15l-3-26.5z"/>
    </g>
</svg>

<style>
  .shirt {
    position: absolute;
    inset: 0;
    width: 100%;
    height: 100%;
    display: block;
  }
</style>

// src/dressing-room/clothes/man-shirt.tsx
import { useState } from 'react';
import { Pattern } from '.';
import styles from './clothes.module.css';

export const ManShirt = () => {
    const [ pattern, setPattern ] = useState('');

    const onSetPatternHandler = (pattern: string) => {
        setPattern(pattern);
    }

    return (
        <svg className={ styles.shirt } viewBox="0 0 48 100" xmlns="http://www.w3.org/2000/svg">
            <defs>
                <Pattern onSetPattern={ onSetPatternHandler }/>
            </defs>
            <g fill={ `url(#${ pattern })`}>
                <path d="m7.24 30.655 5.665.077.219-7.523 2.908 29.637 16.055.119 3.017-29.983.31 7.88 5.274.056.318-9.444s-.643-3.66-2.971-3.894c-2.328-.233-8.909-.711-8.909-.711l-.893-1.632-1.73 1.222-2.436 5.399-2.38-5.715-2.492-.957-1.448 1.311-6.591 1.084s-3.504.085-3.874 2.913c-.37 2.828-.042 10.161-.042 10.161Z"/>
            </g>
        </svg>
    );
};
