// src/dressing-room/components/character.tsx
import { useContext } from 'react';
import { Female, FemaleCensored, Male, MaleCensored } from '../characters';
import { CharacterConfig, Characters } from '../interfaces/characters';
import { ActiveContext } from '../context/active';
import styles from './character.module.css';

interface Props {
    main: boolean;
    genre: string;
}

export const Character = ({ main, genre  }: Props) => {
    const active = useContext(ActiveContext);

    const characterConfigs: Record<Characters, CharacterConfig> = {
        [Characters.FEMALE]: {
            content: <Female active={ active } />
        },
        [Characters.FEMALE_CENSORED]: {
            content: <FemaleCensored />
        },
        [Characters.MALE]: {
            content: <Male active={ active } />
        },
        [Characters.MALE_CENSORED]: {
            content: <MaleCensored />
        }
    }

    const getCharacterConfig = (): Characters => {
        if (genre === Characters.MALE) {
            return main ? Characters.MALE_CENSORED : Characters.MALE;
        } else {
            return main ? Characters.FEMALE_CENSORED : Characters.FEMALE;
        }
    }

    const mainCharacter = getCharacterConfig();

    const mainCharacterConfig = characterConfigs[mainCharacter];

    return (
        <div data-active={ active } className={ styles.character }>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 100">
                { mainCharacterConfig.content }
            </svg>
            <div className={ styles.mask }></div>
        </div>
    );
};

// src/lib/components/Character.svelte

<script lang="ts">
import { Characters } from "../types/characters"
import MaleCensored from "../vectors/MaleCensored.svelte"
import FemaleCensored from "../vectors/FemaleCensored.svelte"
import Male from "../vectors/Male.svelte"
import Female from "../vectors/Female.svelte"
import { genreState } from "../state/state.svelte";

let { active, main } = $props()
</script>

<div data-active={active} class="character">
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 100">>
    {#if genreState.genre === Characters.MALE}
      {#if main}
        <MaleCensored />
      {:else}
        <Male {active} />
      {/if}
    {:else}
      {#if main}
        <FemaleCensored />
      {:else}
        <Female {active} />
      {/if}
    {/if}
  </svg>
  <div class="mask"></div>
</div>

<style>
.character {
  display: grid;
  inset: 0;
  position: absolute;
  transition: transform 700ms cubic-bezier(0,1,.72,.95);
  transform: translateY(100%);
}

.character[data-active='true'] {
  transform: translateY(0);
}

svg {
  justify-self: center;
  margin-inline: auto;
  height: 100%;
}

:global([data-animations="false"]) .character {
  transition: none;
  transition-duration: 0;
}
</style>
